//
// Auto-generated by import-obsidian inside step3-generateSidebar.ts
// Do not edit directly - modifications will be overwritten
//
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  'z2k-templates-docs': [
  {
    "type": "doc",
    "id": "readme",
    "label": "Introduction"
  },
  {
    "type": "category",
    "label": "How-To Guides",
    "items": [
      {
        "type": "category",
        "label": "Getting Started",
        "items": [
          {
            "type": "doc",
            "id": "how-to-guides/getting-started/getting-started-in-two-minutes",
            "label": "Getting Started in Two Minutes"
          },
          {
            "type": "doc",
            "id": "how-to-guides/getting-started/getting-started-in-ten-minutes",
            "label": "Getting Started in Ten Minutes"
          }
        ],
        "link": {
          "type": "doc",
          "id": "how-to-guides/getting-started/getting-started"
        }
      },
      {
        "type": "category",
        "label": "Beginner Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/beginner/beginner"
        }
      },
      {
        "type": "category",
        "label": "Intermediate Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/intermediate/intermediate"
        }
      },
      {
        "type": "category",
        "label": "Advanced Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/advanced/advanced"
        }
      }
    ],
    "link": {
      "type": "doc",
      "id": "how-to-guides/how-to-guides"
    }
  },
  {
    "type": "category",
    "label": "Best Practices",
    "items": [],
    "link": {
      "type": "doc",
      "id": "best-practices/best-practices"
    }
  },
  {
    "type": "category",
    "label": "Reference Manual",
    "items": [
      {
        "type": "category",
        "label": "Template Files",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-files/why-use-templates",
            "label": "Why Use Templates?"
          },
          {
            "type": "doc",
            "id": "reference-manual/template-files/lifecycle-of-a-template",
            "label": "Lifecycle of a Template"
          },
          {
            "type": "doc",
            "id": "reference-manual/template-files/obsidian-commands",
            "label": "Obsidian Commands"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-files/template-files"
        }
      },
      {
        "type": "category",
        "label": "Template Fields",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-fields/template-field-types",
            "label": "Template Field Types"
          },
          {
            "type": "doc",
            "id": "reference-manual/template-fields/template-field-naming-conventions",
            "label": "Template Field Naming Conventions"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-fields/template-fields"
        }
      },
      {
        "type": "category",
        "label": "Template Folders",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-folders/external-template-folders",
            "label": "External Template Folders"
          },
          {
            "type": "doc",
            "id": "reference-manual/template-folders/embedded-template-folders",
            "label": "Embedded Template Folders"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-folders/template-folders"
        }
      },
      {
        "type": "category",
        "label": "Built-In Template Fields",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-date-and-time",
            "label": "Built In Fields - Date and Time"
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-card-data",
            "label": "Built-In Fields - Card Data"
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-card-reference",
            "label": "Built-In Fields - Card Reference"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/built-in-template-fields/built-in-template-fields"
        }
      },
      {
        "type": "category",
        "label": "Data Formatting",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/data-formatting/default-data-formatting",
            "label": "Default Data Formatting"
          },
          {
            "type": "doc",
            "id": "reference-manual/data-formatting/custom-field-formatting",
            "label": "Custom Field Formatting"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/data-formatting/data-formatting"
        }
      },
      {
        "type": "category",
        "label": "Prompting",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/prompting/general-prompting-format",
            "label": "General Prompting Format"
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/prompting-data-types",
            "label": "Prompting Data Types"
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/built-in-prompting-directives",
            "label": "Built-in Prompting Directives"
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/finalizing-and-miss-handling-for-z2k-templates",
            "label": "Finalizing and Miss Handling for Z2K Templates"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/prompting/prompting"
        }
      },
      {
        "type": "category",
        "label": "Handlebars Support",
        "items": [],
        "link": {
          "type": "doc",
          "id": "reference-manual/handlebars-support/handlebars-support"
        }
      },
      {
        "type": "category",
        "label": "Helper Functions",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/helper-functions/helper-functions-usage",
            "label": "Helper Functions Usage"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/helper-functions/helper-functions"
        }
      },
      {
        "type": "category",
        "label": "Built-In Helper Functions",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-formatting",
            "label": "Built-In Functions - Formatting"
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-linking",
            "label": "Built-In Functions - Linking"
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-misc",
            "label": "Built-In Functions - Misc"
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-directives",
            "label": "Built-In Functions - Directives"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/built-in-helper-functions/built-in-helper-functions"
        }
      },
      {
        "type": "category",
        "label": "Partial Templates",
        "items": [],
        "link": {
          "type": "doc",
          "id": "reference-manual/partial-templates/partial-templates"
        }
      },
      {
        "type": "category",
        "label": "Z2K Templates and YAML",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/using-z2k-fields-inside-yaml-metadata",
            "label": "Using Z2K Fields inside YAML Metadata"
          },
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/z2k-system-yaml-files",
            "label": "Z2K System YAML Files"
          },
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/z2k-template-yaml-configuration-fields",
            "label": "Z2K Template YAML Configuration Fields"
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/z2k-templates-and-yaml/z2k-templates-and-yaml"
        }
      },
      {
        "type": "doc",
        "id": "reference-manual/z2k-system-specific-features",
        "label": "Z2K System Specific Features"
      },
      {
        "type": "doc",
        "id": "reference-manual/z2k-templates-uri-and-json",
        "label": "Z2K Templates, URI, and JSON"
      },
      {
        "type": "doc",
        "id": "reference-manual/plugin-settings-page",
        "label": "Plugin Settings Page"
      }
    ],
    "link": {
      "type": "doc",
      "id": "reference-manual/reference-manual"
    }
  },
  {
    "type": "doc",
    "id": "root-level-test-file",
    "label": "Root Level Test File"
  }
]
};

export default sidebars;
