//
// ./sidebars.ts :: Auto-generated by step3 (generateSidebars)
// == Multi Sidebar Mode (single docs plugin instance) ==
// Created on 10/01/2025, 12:46:49 PM PST
// Guardrail: DO NOT add multiple docs plugin instances.
// This file is the single source of truth and will be overwritten.
//
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  Intro: [
    {
      type: "doc",
      id: "markdown-basics",
      label: "Test Jig - Basic Markdown"
    },
    {
      type: "doc",
      id: "markdown-links",
      label: "Test Jig - Markdown Links"
    },
    {
      type: "doc",
      id: "markdown-embedded-links-file-1",
      label: "Test Jig - Embedded Links (File 1)"
    },
    {
      type: "doc",
      id: "markdown-embedded-links-file-2-slug",
      label: "Test Jig - Embedded Links (File 2)"
    },
    {
      type: "doc",
      id: "callouts",
      label: "Test Jig - Callouts"
    },
    {
      type: "ref",
      id: "how-to-guides/getting-started/getting-started-in-two-minutes",
      label: "Getting Started in Two Minutes"
    },
    {
      type: "ref",
      id: "how-to-guides/getting-started/getting-started-in-ten-minutes",
      label: "Getting Started in Ten Minutes"
    },
    {
      type: "ref",
      id: "reference-manual/built-in-template-fields/built-in-template-fields",
      label: "Built-In Template Fields"
    }
  ]
};

export default sidebars;
