//
// Auto-generated by import-obsidian inside step2-buildIndex.ts
// Do not edit directly - modifications will be overwritten

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  'z2k-templates-docs': [
  {
    "type": "category",
    "label": "best-practices",
    "items": [],
    "link": {
      "type": "doc",
      "id": "best-practices/best-practices"
    }
  },
  {
    "type": "category",
    "label": "How-To Guides",
    "items": [
      {
        "type": "category",
        "label": "Advanced Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/advanced/advanced"
        }
      },
      {
        "type": "category",
        "label": "Beginner Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/beginner/beginner"
        }
      },
      {
        "type": "category",
        "label": "Getting Started",
        "items": [
          {
            "type": "doc",
            "id": "how-to-guides/getting-started/getting-started-in-ten-minutes",
            "label": "Getting Started in Ten Minutes",
            "position": 111
          },
          {
            "type": "doc",
            "id": "how-to-guides/getting-started/getting-started-in-two-minutes",
            "label": "Getting Started in Two Minutes",
            "position": 110
          }
        ],
        "link": {
          "type": "doc",
          "id": "how-to-guides/getting-started/getting-started"
        }
      },
      {
        "type": "category",
        "label": "Intermediate Guides",
        "items": [],
        "link": {
          "type": "doc",
          "id": "how-to-guides/intermediate/intermediate"
        }
      }
    ],
    "link": {
      "type": "doc",
      "id": "how-to-guides/how-to-guides"
    }
  },
  {
    "type": "category",
    "label": "Z2K Templates Plugin",
    "items": [
      {
        "type": "doc",
        "id": "reference-manual/plugin-settings-page",
        "label": "Plugin Settings Page",
        "position": 130
      },
      {
        "type": "doc",
        "id": "reference-manual/z2k-system-specific-features",
        "label": "Z2K System Specific Features",
        "position": 111
      },
      {
        "type": "doc",
        "id": "reference-manual/z2k-templates-uri-and-json",
        "label": "Z2K Templates, URI, and JSON",
        "position": 120
      },
      {
        "type": "category",
        "label": "Built-In Helper Functions",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-directives",
            "label": "Built-In Functions - Directives",
            "position": 98
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-formatting",
            "label": "Built-In Functions - Formatting",
            "position": 92
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-linking",
            "label": "Built-In Functions - Linking",
            "position": 94
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-helper-functions/built-in-functions-misc",
            "label": "Built-In Functions - Misc",
            "position": 96
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/built-in-helper-functions/built-in-helper-functions"
        }
      },
      {
        "type": "category",
        "label": "Built-In Template Fields",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-date-and-time",
            "label": "Built In Fields - Date and Time",
            "position": 42
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-card-data",
            "label": "Built-In Fields - Card Data",
            "position": 44
          },
          {
            "type": "doc",
            "id": "reference-manual/built-in-template-fields/built-in-fields-card-reference",
            "label": "Built-In Fields - Card Reference",
            "position": 46
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/built-in-template-fields/built-in-template-fields"
        }
      },
      {
        "type": "category",
        "label": "Data Formatting",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/data-formatting/custom-field-formatting",
            "label": "Custom Field Formatting",
            "position": 54
          },
          {
            "type": "doc",
            "id": "reference-manual/data-formatting/default-data-formatting",
            "label": "Default Data Formatting",
            "position": 52
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/data-formatting/data-formatting"
        }
      },
      {
        "type": "category",
        "label": "Handlebars Support",
        "items": [],
        "link": {
          "type": "doc",
          "id": "reference-manual/handlebars-support/handlebars-support"
        }
      },
      {
        "type": "category",
        "label": "Helper Functions",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/helper-functions/helper-functions-usage",
            "label": "Helper Functions Usage",
            "position": 82
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/helper-functions/helper-functions"
        }
      },
      {
        "type": "category",
        "label": "Partial Templates",
        "items": [],
        "link": {
          "type": "doc",
          "id": "reference-manual/partial-templates/partial-templates"
        }
      },
      {
        "type": "category",
        "label": "Prompting",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/prompting/built-in-prompting-directives",
            "label": "Built-in Prompting Directives",
            "position": 66
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/finalizing-and-miss-handling-for-z2k-templates",
            "label": "Finalizing and Miss Handling for Z2K Templates",
            "position": 68
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/general-prompting-format",
            "label": "General Prompting Format",
            "position": 62
          },
          {
            "type": "doc",
            "id": "reference-manual/prompting/prompting-data-types",
            "label": "Prompting Data Types",
            "position": 64
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/prompting/prompting"
        }
      },
      {
        "type": "category",
        "label": "Template Fields",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-fields/template-field-naming-conventions",
            "label": "Template Field Naming Conventions",
            "position": 24
          },
          {
            "type": "doc",
            "id": "reference-manual/template-fields/template-field-types",
            "label": "Template Field Types",
            "position": 22
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-fields/template-fields"
        }
      },
      {
        "type": "category",
        "label": "Template Files",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-files/lifecycle-of-a-template",
            "label": "Lifecycle of a Template",
            "position": 14
          },
          {
            "type": "doc",
            "id": "reference-manual/template-files/obsidian-commands",
            "label": "Obsidian Commands",
            "position": 16
          },
          {
            "type": "doc",
            "id": "reference-manual/template-files/why-use-templates",
            "label": "Why Use Templates?",
            "position": 12
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-files/template-files"
        }
      },
      {
        "type": "category",
        "label": "Template Folders",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/template-folders/embedded-template-folders",
            "label": "Embedded Template Folders",
            "position": 34
          },
          {
            "type": "doc",
            "id": "reference-manual/template-folders/external-template-folders",
            "label": "External Template Folders",
            "position": 32
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/template-folders/template-folders"
        }
      },
      {
        "type": "category",
        "label": "Z2K Templates and YAML",
        "items": [
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/using-z2k-fields-inside-yaml-metadata",
            "label": "Using Z2K Fields inside YAML Metadata",
            "position": 112
          },
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/z2k-system-yaml-files",
            "label": "Z2K System YAML Files",
            "position": 114
          },
          {
            "type": "doc",
            "id": "reference-manual/z2k-templates-and-yaml/z2k-template-yaml-configuration-fields",
            "label": "Z2K Template YAML Configuration Fields",
            "position": 116
          }
        ],
        "link": {
          "type": "doc",
          "id": "reference-manual/z2k-templates-and-yaml/z2k-templates-and-yaml"
        }
      }
    ],
    "link": {
      "type": "doc",
      "id": "reference-manual/reference-manual"
    }
  },
  {
    "type": "doc",
    "id": "readme",
    "label": "Z2K Templates In-a-Nutshell",
    "position": 1
  },
  {
    "type": "doc",
    "id": "root-level-test-file",
    "label": "Root Level Test File"
  }
]
};

export default sidebars;
